spring:
  mvc:
    servlet:
      path: ${SERVLET_PATH:/backend}
  datasource:
    url: jdbc:postgresql://postgres-service:5432/todo_list
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
